/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-27 18:37:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ferreteriacruz.modelo.Categoria;
import ferreteriacruz.modelo.Usuario;

public final class Categorias_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Categoria");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Usuario");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Usuario usuarioActivo = (Usuario) session.getAttribute("usuarioActivo");
    if (usuarioActivo == null) {
        response.sendRedirect("Login.jsp");
        return;
    }

    List<Categoria> lista = (List<Categoria>) request.getAttribute("listaCategorias");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>FerreteriaCruz | Gestión de Categorías</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/estilos.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        \n");
      out.write("        <div class=\"header-tech\">\n");
      out.write("            <div class=\"header-title\">\n");
      out.write("                <h2 class=\"page-title text-white\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--brand-blue)\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"24\" height=\"24\">\n");
      out.write("                        <path d=\"M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z\"></path>\n");
      out.write("                    </svg>\n");
      out.write("                    Categorías de Hardware\n");
      out.write("                </h2>\n");
      out.write("            </div>\n");
      out.write("            <a href=\"ProductoServlet?accion=nuevo\" class=\"btn-tech\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                    <line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"></line>\n");
      out.write("                    <polyline points=\"12 19 5 12 12 5\"></polyline>\n");
      out.write("                </svg>\n");
      out.write("                Volver a Registro de Producto\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"grid-container mt-20\">\n");
      out.write("            \n");
      out.write("            <div class=\"form-side\">\n");
      out.write("                <h3 class=\"subtitle-blue\">Crear Nueva Familia</h3>\n");
      out.write("                \n");
      out.write("                <form action=\"CategoriaServlet?accion=guardar\" method=\"POST\">\n");
      out.write("                    <label class=\"form-label\">Nombre de la Categoría:</label>\n");
      out.write("                    <input type=\"text\" name=\"txtNombre\" class=\"input-tech\" required placeholder=\"Ej. Monitores, Fuentes de Poder...\" autocomplete=\"off\">\n");
      out.write("                    \n");
      out.write("                    <button type=\"submit\" class=\"btn-submit-tech\">\n");
      out.write("                        Guardar Categoría\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("                \n");
      out.write("                <div class=\"note-box mt-20\">\n");
      out.write("                    <p>\n");
      out.write("                        <strong>Nota:</strong> Las categorías creadas aquí aparecerán automáticamente en el menú desplegable al registrar un nuevo componente en el inventario.\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"table-side\">\n");
      out.write("                <div class=\"d-flex justify-between align-center mb-15\">\n");
      out.write("                    <h3 class=\"text-white font-bold\">Familias Registradas</h3>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"search-box-container\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#6b7280\" stroke-width=\"2\" width=\"16\" height=\"16\">\n");
      out.write("                        <circle cx=\"11\" cy=\"11\" r=\"8\"></circle>\n");
      out.write("                        <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    <input type=\"text\" id=\"buscadorCat\" class=\"input-tech\" placeholder=\"Buscar familia...\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"table-panel\">\n");
      out.write("                    <table class=\"tech-table\" id=\"tablaCat\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>ID</th>\n");
      out.write("                                <th>NOMBRE DE FAMILIA / CATEGORÍA</th>\n");
      out.write("                                <th class=\"text-center\">ACCIONES</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            ");

                                if(lista != null && !lista.isEmpty()) {
                                    for(Categoria c : lista) {
                            
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td class=\"td-id\">#");
      out.print( String.format("%03d", c.getIdCategoria()) );
      out.write("</td>\n");
      out.write("                                <td class=\"td-nombre\">");
      out.print( c.getNombre() );
      out.write("</td>\n");
      out.write("                                <td class=\"text-center\">\n");
      out.write("                                    <a href=\"CategoriaServlet?accion=eliminar&id=");
      out.print( c.getIdCategoria() );
      out.write("\" class=\"btn-action btn-delete\" onclick=\"return confirm('¿Eliminar la categoría ");
      out.print( c.getNombre() );
      out.write("? Asegúrese de que no haya productos usándola.');\">Eliminar</a>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                            ");

                                    }
                                } else {
                            
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td colspan=\"3\" class=\"text-center p-30\">\n");
      out.write("                                    <p class=\"text-muted text-sm\">No hay categorías registradas.</p>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/utils.js\"></script>\n");
      out.write("    <script>inicializarBuscador('buscadorCat', 'tablaCat');</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
