/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-27 18:57:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ferreteriacruz.modelo.Producto;
import ferreteriacruz.modelo.Usuario;

public final class Inventario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("ferreteriacruz.modelo.Producto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Usuario");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Usuario usuarioActivo = (Usuario) session.getAttribute("usuarioActivo");
    if (usuarioActivo == null) {
        response.sendRedirect("Login.jsp");
        return;
    }
    
    List<Producto> lista = (List<Producto>) request.getAttribute("productos");
    
    int totalStock = 0;
    int alertasStock = 0;
    double valorInventario = 0.0;
    
    if(lista != null && !lista.isEmpty()) {
        for(Producto p : lista) {
            totalStock += p.getStockActual();
            valorInventario += (p.getStockActual() * p.getPrecio());
            if(p.getStockActual() <= p.getStockMinimo()) {
                alertasStock++;
            }
        }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>FerreteriaCruz | Inventario General</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@500;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/estilos.css\">\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    \n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        \n");
      out.write("        <div class=\"header-tech\">\n");
      out.write("            <div class=\"header-title\">\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/logo_ferreteriacruz.png\" alt=\"FerreteriaCruz\" class=\"logo-img\" onerror=\"this.src='https://via.placeholder.com/150x45/111827/E63946?text=FERRETERIACRUZ'\">\n");
      out.write("                <h2 class=\"text-white\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"24\" height=\"24\" class=\"text-blue\">\n");
      out.write("                        <rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" ry=\"2\"></rect>\n");
      out.write("                        <line x1=\"8\" y1=\"21\" x2=\"16\" y2=\"21\"></line>\n");
      out.write("                        <line x1=\"12\" y1=\"17\" x2=\"12\" y2=\"21\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    Stock y Componentes\n");
      out.write("                </h2>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"nav-links\">\n");
      out.write("                <div class=\"user-badge\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--brand-blue)\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                        <path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"></path>\n");
      out.write("                        <circle cx=\"12\" cy=\"7\" r=\"4\"></circle>\n");
      out.write("                    </svg>\n");
      out.write("                    Operador: <strong>");
      out.print( usuarioActivo.getUsername() );
      out.write("</strong> (");
      out.print( usuarioActivo.getRol() );
      out.write(")\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <a href=\"ProductoServlet?accion=nuevo\" class=\"btn-tech btn-success-tech\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                        <line x1=\"12\" y1=\"5\" x2=\"12\" y2=\"19\"></line>\n");
      out.write("                        <line x1=\"5\" y1=\"12\" x2=\"19\" y2=\"12\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    Añadir Producto\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"ProductoServlet?accion=listar\" class=\"btn-tech\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                        <polyline points=\"23 4 23 10 17 10\"></polyline>\n");
      out.write("                        <polyline points=\"1 20 1 14 7 14\"></polyline>\n");
      out.write("                        <path d=\"M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15\"></path>\n");
      out.write("                    </svg>\n");
      out.write("                    Sincronizar (Refresh)\n");
      out.write("                </a>\n");
      out.write("                \n");
      out.write("                <a href=\"LoginServlet?accion=logout\" class=\"btn-tech btn-danger-tech\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                        <path d=\"M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4\"></path>\n");
      out.write("                        <polyline points=\"16 17 21 12 16 7\"></polyline>\n");
      out.write("                        <line x1=\"21\" y1=\"12\" x2=\"9\" y2=\"12\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    Desconectar\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"main-nav\">\n");
      out.write("            <a href=\"ProductoServlet?accion=listar\" class=\"nav-btn nav-active\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"3\" y=\"3\" width=\"7\" height=\"7\"></rect><rect x=\"14\" y=\"3\" width=\"7\" height=\"7\"></rect><rect x=\"14\" y=\"14\" width=\"7\" height=\"7\"></rect><rect x=\"3\" y=\"14\" width=\"7\" height=\"7\"></rect></svg>\n");
      out.write("                Inventario General\n");
      out.write("            </a>\n");
      out.write("            <a href=\"Venta.jsp\" class=\"nav-btn\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"9\" cy=\"21\" r=\"1\"></circle><circle cx=\"20\" cy=\"21\" r=\"1\"></circle><path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"></path></svg>\n");
      out.write("                Punto de Venta / Salida\n");
      out.write("            </a>\n");
      out.write("            <a href=\"MermaServlet?accion=listar\" class=\"nav-btn\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polygon points=\"7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2\"></polygon><line x1=\"15\" y1=\"9\" x2=\"9\" y2=\"15\"></line><line x1=\"9\" y1=\"9\" x2=\"15\" y2=\"15\"></line></svg>\n");
      out.write("                Gestión de Mermas\n");
      out.write("            </a>\n");
      out.write("            <a href=\"KardexServlet?accion=listar\" class=\"nav-btn\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"></path><polyline points=\"14 2 14 8 20 8\"></polyline><line x1=\"16\" y1=\"13\" x2=\"8\" y2=\"13\"></line><line x1=\"16\" y1=\"17\" x2=\"8\" y2=\"17\"></line><polyline points=\"10 9 9 9 8 9\"></polyline></svg>\n");
      out.write("                Auditar Kardex\n");
      out.write("            </a>\n");
      out.write("            <a href=\"UsuarioServlet?accion=listar\" class=\"nav-btn\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"></path><circle cx=\"9\" cy=\"7\" r=\"4\"></circle><path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"></path><path d=\"M16 3.13a4 4 0 0 1 0 7.75\"></path></svg>\n");
      out.write("                Usuarios\n");
      out.write("            </a>\n");
      out.write("            <a href=\"ReporteServlet\" class=\"nav-btn\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"18\" y1=\"20\" x2=\"18\" y2=\"10\"></line><line x1=\"12\" y1=\"20\" x2=\"12\" y2=\"4\"></line><line x1=\"6\" y1=\"20\" x2=\"6\" y2=\"14\"></line></svg>\n");
      out.write("                Reportes Gerenciales\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"kpi-container\">\n");
      out.write("            \n");
      out.write("            <div class=\"kpi-card\">\n");
      out.write("                <div class=\"kpi-icon-wrapper kpi-icon-blue\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"28\" height=\"28\"><path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"></path><polyline points=\"3.27 6.96 12 12.01 20.73 6.96\"></polyline><line x1=\"12\" y1=\"22.08\" x2=\"12\" y2=\"12\"></line></svg>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <p class=\"kpi-title\">Volumen Físico</p>\n");
      out.write("                    <h3 class=\"kpi-value text-white\">");
      out.print( totalStock );
      out.write(" <span class=\"kpi-unit\">Unidades</span></h3>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"kpi-card\">\n");
      out.write("                <div class=\"kpi-icon-wrapper kpi-icon-red\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"28\" height=\"28\"><path d=\"M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z\"></path><line x1=\"12\" y1=\"9\" x2=\"12\" y2=\"13\"></line><line x1=\"12\" y1=\"17\" x2=\"12.01\" y2=\"17\"></line></svg>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <p class=\"kpi-title\">Estado Crítico</p>\n");
      out.write("                    <h3 class=\"kpi-value text-danger\">");
      out.print( alertasStock );
      out.write(" <span class=\"kpi-unit\">SKUs en Riesgo</span></h3>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"kpi-card\">\n");
      out.write("                <div class=\"kpi-icon-wrapper kpi-icon-green\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"28\" height=\"28\"><line x1=\"12\" y1=\"1\" x2=\"12\" y2=\"23\"></line><path d=\"M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6\"></path></svg>\n");
      out.write("                </div>\n");
      out.write("                <div>\n");
      out.write("                    <p class=\"kpi-title\">Valorización (Activos)</p>\n");
      out.write("                    <h3 class=\"kpi-value text-success\">S/ ");
      out.print( String.format("%,.2f", valorInventario) );
      out.write("</h3>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"search-box-container\">\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--brand-blue)\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"20\" height=\"20\"><circle cx=\"11\" cy=\"11\" r=\"8\"></circle><line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line></svg>\n");
      out.write("            <input type=\"text\" id=\"buscadorInventario\" placeholder=\"Buscar por SKU, Especificación o Estado...\" class=\"input-tech\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"table-panel\" style=\"max-height: none;\">\n");
      out.write("            <table class=\"tech-table\" id=\"tablaInventario\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th width=\"60\">ID</th>\n");
      out.write("                        <th width=\"15%\">CÓDIGO SKU</th>\n");
      out.write("                        <th class=\"text-center\" width=\"120\">FOTO</th>\n");
      out.write("                        <th width=\"30%\">ESPECIFICACIÓN DE COMPONENTE</th>\n");
      out.write("                        <th class=\"text-center\">STOCK ACTUAL</th>\n");
      out.write("                        <th class=\"text-center\">UMBRAL MÍN.</th>\n");
      out.write("                        <th>PRECIO UNIT.</th>\n");
      out.write("                        <th>ESTADO</th>\n");
      out.write("                        <th class=\"text-center\">ACCIONES</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");

                        if(lista != null && !lista.isEmpty()) {
                            for(Producto p : lista) {
                                boolean enAlerta = p.getStockActual() <= p.getStockMinimo();
                                String claseStock = enAlerta ? "stock-low" : "stock-good";
                    
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"td-id\">#");
      out.print( String.format("%03d", p.getIdProducto()) );
      out.write("</td>\n");
      out.write("                        <td><span class=\"sku-box\">");
      out.print( p.getCodigoSKU() );
      out.write("</span></td>\n");
      out.write("                        \n");
      out.write("                        <td class=\"text-center\">\n");
      out.write("                            ");
 if(p.getBase64Imagen() != null) { 
      out.write("\n");
      out.write("                                <img src=\"data:image/jpeg;base64,");
      out.print( p.getBase64Imagen() );
      out.write("\" class=\"product-img\" alt=\"");
      out.print( p.getNombre() );
      out.write("\">\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("                                <div class=\"no-photo\">Sin Foto</div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        \n");
      out.write("                        <td class=\"td-nombre\">");
      out.print( p.getNombre() );
      out.write("</td>\n");
      out.write("                        \n");
      out.write("                        <td class=\"text-center\">\n");
      out.write("                            <span class=\"stock-number ");
      out.print( claseStock );
      out.write('"');
      out.write('>');
      out.print( p.getStockActual() );
      out.write("</span>\n");
      out.write("                        </td>\n");
      out.write("                        \n");
      out.write("                        <td class=\"text-center text-muted font-mono\">\n");
      out.write("                            ");
      out.print( p.getStockMinimo() );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        \n");
      out.write("                        <td class=\"td-precio\">S/ ");
      out.print( String.format("%,.2f", p.getPrecio()) );
      out.write("</td>\n");
      out.write("                        \n");
      out.write("                        <td>\n");
      out.write("                            ");
 if(!enAlerta) { 
      out.write("\n");
      out.write("                                <span class=\"badge badge-optimal\">ÓPTIMO</span>\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("                                <span class=\"badge badge-alert\">ALERTA</span>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        \n");
      out.write("                        <td>\n");
      out.write("                            <div class=\"actions-container\">\n");
      out.write("                                <a href=\"ProductoServlet?accion=editar&id=");
      out.print( p.getIdProducto() );
      out.write("\" class=\"btn-action btn-edit\" style=\"min-width: 80px;\">Editar</a>\n");
      out.write("                                <a href=\"ProductoServlet?accion=eliminar&id=");
      out.print( p.getIdProducto() );
      out.write("\" class=\"btn-action btn-delete\" style=\"min-width: 80px;\" onclick=\"return confirm('¿Está seguro de eliminar el SKU: ");
      out.print( p.getCodigoSKU() );
      out.write("?');\">Eliminar</a>\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");

                            }
                        } else {
                    
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td colspan=\"9\" class=\"text-center p-30\">\n");
      out.write("                            <h4 class=\"text-muted m-0\">No hay datos para mostrar en el inventario.</h4>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("                \n");
      out.write("    </div>\n");
      out.write("                \n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/utils.js\"></script>\n");
      out.write("    <script>inicializarBuscador('buscadorInventario', 'tablaInventario');</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
