/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-27 18:59:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ferreteriacruz.modelo.MovimientoKardex;
import ferreteriacruz.modelo.Usuario;

public final class Kardex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Usuario");
    _jspx_imports_classes.add("ferreteriacruz.modelo.MovimientoKardex");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Usuario usuarioActivo = (Usuario) session.getAttribute("usuarioActivo");
    if (usuarioActivo == null) {
        response.sendRedirect("Login.jsp");
        return;
    }
    List<MovimientoKardex> historial = (List<MovimientoKardex>) request.getAttribute("historialKardex");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>FerreteriaCruz | Trazabilidad Kardex</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@500;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/estilos.css\">\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    \n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        \n");
      out.write("        <div class=\"header-tech\">\n");
      out.write("            <div class=\"header-title\">\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/logo_ferreteriacruz.png\" alt=\"FerreteriaCruz\" class=\"logo-img\" onerror=\"this.src='https://via.placeholder.com/150x45/111827/E63946?text=FERRETERIACRUZ'\">\n");
      out.write("                <h2 class=\"text-white\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"24\" height=\"24\" class=\"text-blue\">\n");
      out.write("                        <path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"></path>\n");
      out.write("                        <polyline points=\"3.27 6.96 12 12.01 20.73 6.96\"></polyline>\n");
      out.write("                        <line x1=\"12\" y1=\"22.08\" x2=\"12\" y2=\"12\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    Trazabilidad de Activos\n");
      out.write("                </h2>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <a href=\"ProductoServlet?accion=listar\" class=\"btn-tech\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                    <line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"></line>\n");
      out.write("                    <polyline points=\"12 19 5 12 12 5\"></polyline>\n");
      out.write("                </svg>\n");
      out.write("                Volver al Almacén\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"search-box-container mt-15 mb-15\">\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--brand-blue)\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"20\" height=\"20\">\n");
      out.write("                <circle cx=\"11\" cy=\"11\" r=\"8\"></circle>\n");
      out.write("                <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line>\n");
      out.write("            </svg>\n");
      out.write("            <input type=\"text\" id=\"buscadorKardex\" placeholder=\"Buscar por Operación, S/N, Hardware o Responsable...\" class=\"input-tech\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"table-panel\">\n");
      out.write("            <table class=\"tech-table\" id=\"tablaKardex\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>FECHA / HORA</th>\n");
      out.write("                        <th>OPERACIÓN</th>\n");
      out.write("                        <th>HARDWARE AFECTADO</th>\n");
      out.write("                        <th>CANT.</th>\n");
      out.write("                        <th>JUSTIFICACIÓN / S/N</th>\n");
      out.write("                        <th>RESPONSABLE</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");

                        if (historial != null && !historial.isEmpty()) {
                            for (MovimientoKardex k : historial) {
                                
                                String claseBadge = "badge-in";
                                String claseSN = "";
                                String icono = "<line x1='12' y1='19' x2='12' y2='5'></line><polyline points='5 12 12 5 19 12'></polyline>";
                                String signo = "+";
                                String classColorCant = "text-success"; // Dinámico a clases CSS

                                if(k.getTipoMovimiento().equals("SALIDA")) { 
                                    claseBadge = "badge-out"; 
                                    icono = "<line x1='5' y1='12' x2='19' y2='12'></line><polyline points='12 5 19 12 12 19'></polyline>";
                                    signo = "-";
                                    classColorCant = "text-blue";
                                } else if(k.getTipoMovimiento().equals("MERMA")) { 
                                    claseBadge = "badge-merma"; 
                                    claseSN = "sn-red";
                                    icono = "<path d='M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z'></path><line x1='12' y1='9' x2='12' y2='13'></line><line x1='12' y1='17' x2='12.01' y2='17'></line>";
                                    signo = "-";
                                    classColorCant = "text-danger";
                                }
                    
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"text-muted text-sm\">\n");
      out.write("                            ");
      out.print( k.getFecha().toString().substring(0, 10) );
      out.write("<br>\n");
      out.write("                            <strong class=\"text-white\">");
      out.print( k.getFecha().toString().substring(11, 19) );
      out.write("</strong>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <span class=\"badge ");
      out.print( claseBadge );
      out.write("\">\n");
      out.write("                                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"12\" height=\"12\">");
      out.print( icono );
      out.write("</svg>\n");
      out.write("                                ");
      out.print( k.getTipoMovimiento() );
      out.write("\n");
      out.write("                            </span>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <div class=\"font-bold text-white\">");
      out.print( k.getNombreProducto() );
      out.write("</div>\n");
      out.write("                            ");
 if(k.getMotivo().contains("S/N")) { 
      out.write("\n");
      out.write("                                <div class=\"sn-box ");
      out.print( claseSN );
      out.write("\">\n");
      out.write("                                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"12\" height=\"12\" style=\"display: inline-block; vertical-align: middle; margin-right: 3px;\">\n");
      out.write("                                        <path d=\"M4 5h16v14H4z\"/>\n");
      out.write("                                        <line x1=\"8\" y1=\"5\" x2=\"8\" y2=\"19\"/>\n");
      out.write("                                        <line x1=\"16\" y1=\"5\" x2=\"16\" y2=\"19\"/>\n");
      out.write("                                    </svg>\n");
      out.write("                                    Trazabilidad S/N Activa\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td class=\"font-bold ");
      out.print( classColorCant );
      out.write("\" style=\"font-size: 15px;\">\n");
      out.write("                            ");
      out.print( signo );
      out.print( k.getCantidad() );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td class=\"text-muted text-sm\" style=\"max-width: 250px; line-height: 1.5;\">\n");
      out.write("                            ");
      out.print( k.getMotivo() );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <div class=\"user-badge m-0\" style=\"display: inline-flex;\">\n");
      out.write("                                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"14\" height=\"14\" class=\"text-muted\">\n");
      out.write("                                    <path d=\"M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2\"></path>\n");
      out.write("                                    <circle cx=\"12\" cy=\"7\" r=\"4\"></circle>\n");
      out.write("                                </svg>\n");
      out.write("                                <strong>");
      out.print( k.getNombreUsuario() );
      out.write("</strong>\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");
      }
                        } else {
                    
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td colspan=\"6\" class=\"text-center p-30\">\n");
      out.write("                            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--border-tech)\" stroke-width=\"1\" width=\"60\" height=\"60\" class=\"mb-15\">\n");
      out.write("                                <path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"></path>\n");
      out.write("                            </svg>\n");
      out.write("                            <h4 class=\"text-muted m-0\">Kardex Vacío</h4>\n");
      out.write("                            <p class=\"text-muted text-sm mt-0\">Aún no hay operaciones registradas en la base de datos.</p>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/utils.js\"></script>\n");
      out.write("    <script>inicializarBuscador('buscadorKardex', 'tablaKardex');</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
