/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-27 18:59:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ferreteriacruz.modelo.Series;
import ferreteriacruz.modelo.Usuario;

public final class Mermas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Usuario");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Series");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Usuario usuarioActivo = (Usuario) session.getAttribute("usuarioActivo");
    if (usuarioActivo == null) {
        response.sendRedirect("Login.jsp");
        return;
    }
    List<Series> disponibles = (List<Series>) request.getAttribute("seriesDisponibles");
    List<Series> mermadas = (List<Series>) request.getAttribute("seriesMermadas");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>FerreteriaCruz | Gestión de Mermas</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/estilos.css\">\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        \n");
      out.write("        <div class=\"header-tech\">\n");
      out.write("            <div class=\"header-title\">\n");
      out.write("                <h2>\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#ef4444\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width: 24px; height: 24px;\">\n");
      out.write("                        <polygon points=\"7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2\"></polygon>\n");
      out.write("                        <line x1=\"15\" y1=\"9\" x2=\"9\" y2=\"15\"></line>\n");
      out.write("                        <line x1=\"9\" y1=\"9\" x2=\"15\" y2=\"15\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    Gestión de Mermas (Bajas de Hardware)\n");
      out.write("                </h2>\n");
      out.write("            </div>\n");
      out.write("            <a href=\"ProductoServlet?accion=listar\" class=\"btn-tech\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                    <line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"></line>\n");
      out.write("                    <polyline points=\"12 19 5 12 12 5\"></polyline>\n");
      out.write("                </svg>\n");
      out.write("                Volver al Inventario\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"grid-container\">\n");
      out.write("            \n");
      out.write("            <div class=\"form-side\">\n");
      out.write("                <h3 class=\"subtitle-blue\">1. Componentes Activos (Seleccione para dar de baja)</h3>\n");
      out.write("                \n");
      out.write("                <div class=\"search-box-container mb-15\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#6b7280\" stroke-width=\"2\" width=\"16\" height=\"16\">\n");
      out.write("                        <circle cx=\"11\" cy=\"11\" r=\"8\"></circle>\n");
      out.write("                        <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    <input type=\"text\" id=\"buscadorDisp\" placeholder=\"Buscar por Nro Serie o SKU...\" class=\"input-tech m-0\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"table-panel\">\n");
      out.write("                    <table class=\"tech-table\" id=\"tablaDisp\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>CÓDIGO SKU</th>\n");
      out.write("                                <th>PRODUCTO</th>\n");
      out.write("                                <th>NÚMERO SERIE (S/N)</th>\n");
      out.write("                                <th class=\"text-center\">ACCIÓN</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            ");
 if(disponibles != null && !disponibles.isEmpty()) { 
                                   for(Series s : disponibles) { 
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td class=\"font-mono text-muted text-xs\">");
      out.print( s.getCodigoSKU() );
      out.write("</td>\n");
      out.write("                                <td class=\"td-nombre\">");
      out.print( s.getNombreProducto() );
      out.write("</td>\n");
      out.write("                                <td class=\"font-mono text-success font-bold\">");
      out.print( s.getNumeroSerie() );
      out.write("</td>\n");
      out.write("                                <td class=\"text-center\">\n");
      out.write("                                    <button type=\"button\" onclick=\"ejecutarMerma('");
      out.print( s.getNumeroSerie() );
      out.write("')\" class=\"btn-action btn-delete\">\n");
      out.write("                                        Mermar\n");
      out.write("                                    </button>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                            ");
 }} else { 
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td colspan=\"4\" class=\"text-center p-20 text-muted\">No hay componentes disponibles para dar de baja</td>\n");
      out.write("                            </tr>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-side\">\n");
      out.write("                <h3 class=\"subtitle-red\">2. Historial de Equipos Defectuosos</h3>\n");
      out.write("                \n");
      out.write("                <div class=\"search-box-container mb-15\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#6b7280\" stroke-width=\"2\" width=\"16\" height=\"16\">\n");
      out.write("                        <circle cx=\"11\" cy=\"11\" r=\"8\"></circle>\n");
      out.write("                        <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    <input type=\"text\" id=\"buscadorMerma\" placeholder=\"Buscar en bajas...\" class=\"input-tech m-0\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"table-panel\">\n");
      out.write("                    <table class=\"tech-table\" id=\"tablaMerma\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>CÓDIGO SKU</th>\n");
      out.write("                                <th>PRODUCTO</th>\n");
      out.write("                                <th>NÚMERO SERIE (S/N)</th>\n");
      out.write("                                <th class=\"text-center\">ESTADO</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            ");
 if(mermadas != null && !mermadas.isEmpty()) { 
                                   for(Series m : mermadas) { 
      out.write("\n");
      out.write("                            <tr class=\"row-disabled\">\n");
      out.write("                                <td class=\"font-mono text-muted text-xs\">");
      out.print( m.getCodigoSKU() );
      out.write("</td>\n");
      out.write("                                <td class=\"td-nombre\">");
      out.print( m.getNombreProducto() );
      out.write("</td>\n");
      out.write("                                <td class=\"font-mono text-danger\" style=\"text-decoration: line-through;\">");
      out.print( m.getNumeroSerie() );
      out.write("</td>\n");
      out.write("                                <td class=\"text-center\">\n");
      out.write("                                    <span class=\"badge badge-merma\">MERMA</span>\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                            ");
 }} else { 
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                                <td colspan=\"4\" class=\"text-center p-20 text-muted\">Inventario limpio (No hay mermas registradas)</td>\n");
      out.write("                            </tr>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <form id=\"frmProcesarMerma\" action=\"MermaServlet\" method=\"POST\" style=\"display: none;\">\n");
      out.write("        <input type=\"hidden\" name=\"txtNroSerie\" id=\"hdnNroSerie\">\n");
      out.write("        <input type=\"hidden\" name=\"txtMotivo\" id=\"hdnMotivo\">\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/utils.js\"></script>\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/mermas.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
