/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-27 18:37:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import ferreteriacruz.modelo.Producto;
import ferreteriacruz.modelo.Usuario;
import java.util.List;
import ferreteriacruz.modelo.Categoria;

public final class ProductoForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("ferreteriacruz.modelo.Producto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Categoria");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Usuario");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Usuario usuarioActivo = (Usuario) session.getAttribute("usuarioActivo");
    if (usuarioActivo == null) {
        response.sendRedirect("Login.jsp");
        return;
    }

    Producto p = (Producto) request.getAttribute("producto");
    boolean esEdicion = (p != null);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>FerreteriaCruz | Registro de Hardware</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/estilos.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-container-narrow\">\n");
      out.write("        \n");
      out.write("        <div class=\"header-tech\">\n");
      out.write("            <div class=\"header-title\">\n");
      out.write("                <h2>\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--brand-blue)\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width: 24px; height: 24px;\">\n");
      out.write("                        <path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"></path>\n");
      out.write("                    </svg>\n");
      out.write("                    ");
      out.print( esEdicion ? "Modificar Componente" : "Registrar Nuevo Componente" );
      out.write("\n");
      out.write("                </h2>\n");
      out.write("            </div>\n");
      out.write("            <a href=\"ProductoServlet?accion=listar\" class=\"btn-tech\">Cancelar y Volver</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"form-panel\">\n");
      out.write("            <form action=\"ProductoServlet?accion=guardar\" method=\"POST\" enctype=\"multipart/form-data\">\n");
      out.write("                \n");
      out.write("                <input type=\"hidden\" name=\"txtId\" value=\"");
      out.print( esEdicion ? p.getIdProducto() : "" );
      out.write("\">\n");
      out.write("\n");
      out.write("                <label class=\"form-label\">Código SKU único:</label>\n");
      out.write("                <input type=\"text\" name=\"txtSku\" class=\"input-tech input-mono\" required placeholder=\"Ej. GPU-NV-4090\" value=\"");
      out.print( esEdicion ? p.getCodigoSKU() : "" );
      out.write("\">\n");
      out.write("\n");
      out.write("                <label class=\"form-label\">Nombre / Especificación del Producto:</label>\n");
      out.write("                <input type=\"text\" name=\"txtNombre\" class=\"input-tech\" required placeholder=\"Ej. NVIDIA RTX 4090 24GB\" value=\"");
      out.print( esEdicion ? p.getNombre() : "" );
      out.write("\">\n");
      out.write("                \n");
      out.write("                <label class=\"form-label\">Familia / Categoría del Componente:</label>\n");
      out.write("                <div class=\"d-flex align-center gap-15 mb-25\">\n");
      out.write("                    <select name=\"cboCategoria\" class=\"input-tech flex-col\" style=\"margin-bottom: 0;\" required>\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                        ");
 
                           List<Categoria> cats = (List<Categoria>) request.getAttribute("listaCategorias");
                           if(cats != null) {
                               for(Categoria c : cats) {
                                   String seleccionado = (esEdicion && p.getIdCategoria() == c.getIdCategoria()) ? "selected" : "";
                        
      out.write("\n");
      out.write("                                <option value=\"");
      out.print( c.getIdCategoria() );
      out.write('"');
      out.write(' ');
      out.print( seleccionado );
      out.write('>');
      out.print( c.getNombre() );
      out.write("</option>\n");
      out.write("                        ");
     }
                           } 
                        
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                    <a href=\"CategoriaServlet?accion=listar\" class=\"btn-action btn-edit\" style=\"padding: 14px 20px; font-size: 14px;\">Gestionar Categorías</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"flex-row gap-15\">\n");
      out.write("                    <div class=\"flex-col\">\n");
      out.write("                        <label class=\"form-label\">Stock Inicial/Actual:</label>\n");
      out.write("                        <input type=\"number\" name=\"txtStock\" class=\"input-tech input-mono\" required min=\"0\" value=\"");
      out.print( esEdicion ? p.getStockActual() : "0" );
      out.write("\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"flex-col\">\n");
      out.write("                        <label class=\"form-label\">Umbral de Alerta Mínimo:</label>\n");
      out.write("                        <input type=\"number\" name=\"txtMinimo\" class=\"input-tech input-mono\" required min=\"0\" value=\"");
      out.print( esEdicion ? p.getStockMinimo() : "5" );
      out.write("\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <label class=\"form-label\">Precio Unitario (S/):</label>\n");
      out.write("                <input type=\"number\" name=\"txtPrecio\" class=\"input-tech input-mono\" step=\"0.01\" required placeholder=\"Ej. 1500.50\" value=\"");
      out.print( esEdicion ? p.getPrecio() : "" );
      out.write("\">\n");
      out.write("\n");
      out.write("                <label class=\"form-label mt-15\">Fotografía del Componente (Opcional):</label>\n");
      out.write("                <input type=\"file\" name=\"txtImagen\" class=\"input-tech\" accept=\"image/png, image/jpeg, image/webp\">\n");
      out.write("                \n");
      out.write("                ");
 if(esEdicion && p.getBase64Imagen() != null) { 
      out.write("\n");
      out.write("                    <div class=\"info-box mt-15\" style=\"display: inline-flex; flex-direction: column; align-items: flex-start; padding: 15px;\">\n");
      out.write("                        <img src=\"data:image/jpeg;base64,");
      out.print( p.getBase64Imagen() );
      out.write("\" class=\"product-img\" style=\"width: auto; height: 100px; padding: 0;\">\n");
      out.write("                        <p class=\"text-muted text-xs font-bold\" style=\"margin: 10px 0 0 0;\">Imagen Actual (Suba otra si desea reemplazarla)</p>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn-submit-tech mt-20\">\n");
      out.write("                    ");
      out.print( esEdicion ? "Actualizar Datos de Hardware" : "Guardar Nuevo Hardware" );
      out.write("\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
