/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-27 18:59:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Map;
import ferreteriacruz.modelo.Venta;
import ferreteriacruz.modelo.Usuario;

public final class Reportes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Usuario");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Venta");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Usuario usuarioActivo = (Usuario) session.getAttribute("usuarioActivo");
    if (usuarioActivo == null) {
        response.sendRedirect("Login.jsp");
        return;
    }

    Map<String, Integer> kpis = (Map<String, Integer>) request.getAttribute("kpis");
    if(kpis == null) { 
        kpis = new java.util.HashMap<>(); 
        kpis.put("totalStock", 0); kpis.put("totalVentas", 0); kpis.put("totalMermas", 0); kpis.put("stockCritico", 0); 
    }
    
    int totalStock = kpis.get("totalStock");
    int totalVentas = kpis.get("totalVentas");
    int totalMermas = kpis.get("totalMermas");
    int stockCritico = kpis.get("stockCritico");
    int stockOptimo = totalStock - stockCritico;
    
    Double ingresos = (Double) request.getAttribute("ingresosTotales");
    if(ingresos == null) ingresos = 0.0;
    
    String topLabels = (String) request.getAttribute("topLabels");
    String topData = (String) request.getAttribute("topData");
    String catLabels = (String) request.getAttribute("catLabels");
    String catData = (String) request.getAttribute("catData");
    
    List<Venta> ultimasVentas = (List<Venta>) request.getAttribute("ultimasVentas");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>FerreteriaCruz | Intelligence Dashboard</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@500;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/estilos.css\">\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        \n");
      out.write("        <div class=\"header-tech\">\n");
      out.write("            <div class=\"header-title\">\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/logo_ferreteriacruz.png\" alt=\"FerreteriaCruz\" class=\"logo-img\">\n");
      out.write("                <h2>\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--brand-blue)\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"24\" height=\"24\" style=\"vertical-align: bottom;\">\n");
      out.write("                        <rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\" ry=\"2\"></rect>\n");
      out.write("                        <line x1=\"3\" y1=\"9\" x2=\"21\" y2=\"9\"></line>\n");
      out.write("                        <line x1=\"9\" y1=\"21\" x2=\"9\" y2=\"9\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    Business Intelligence (BI) Dashboard\n");
      out.write("                </h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-links\">\n");
      out.write("                <div class=\"user-badge\" style=\"background: rgba(16, 185, 129, 0.1); border: 1px solid rgba(16, 185, 129, 0.3); color: #10b981;\">\n");
      out.write("                    Ingresos Netos: <strong class=\"font-mono\">S/ ");
      out.print( String.format("%,.2f", ingresos) );
      out.write("</strong>\n");
      out.write("                </div>\n");
      out.write("                <a href=\"ProductoServlet?accion=listar\" class=\"btn-tech\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                        <line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"></line>\n");
      out.write("                        <polyline points=\"12 19 5 12 12 5\"></polyline>\n");
      out.write("                    </svg>\n");
      out.write("                    Volver al Menú Principal\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"report-grid\">\n");
      out.write("            <div class=\"report-card card-blue\">\n");
      out.write("                <div class=\"report-label\">Hardware en Stock Total</div>\n");
      out.write("                <div class=\"report-value\">");
      out.print( totalStock );
      out.write("</div>\n");
      out.write("                <span class=\"text-blue text-xs font-bold\">↑ Unidades Físicas Activas</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"report-card card-green\">\n");
      out.write("                <div class=\"report-label\">Ventas Concretadas</div>\n");
      out.write("                <div class=\"report-value\">");
      out.print( totalVentas );
      out.write("</div>\n");
      out.write("                <span class=\"text-success text-xs font-bold\">✔ Salidas Procesadas</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"report-card card-red\">\n");
      out.write("                <div class=\"report-label\">Productos en Merma</div>\n");
      out.write("                <div class=\"report-value\">");
      out.print( totalMermas );
      out.write("</div>\n");
      out.write("                <span class=\"text-danger text-xs font-bold\">⚠ Equipos Defectuosos</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"report-card card-yellow\">\n");
      out.write("                <div class=\"report-label\">Alertas Críticas</div>\n");
      out.write("                <div class=\"report-value\">");
      out.print( stockCritico );
      out.write("</div>\n");
      out.write("                <span class=\"text-warning text-xs font-bold\">↓ SKUs por debajo del mínimo</span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"charts-container\">\n");
      out.write("            <div class=\"chart-box\" style=\"flex: 1.5;\">\n");
      out.write("                <div class=\"chart-title\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"18\" height=\"18\">\n");
      out.write("                        <line x1=\"18\" y1=\"20\" x2=\"18\" y2=\"10\"></line>\n");
      out.write("                        <line x1=\"12\" y1=\"20\" x2=\"12\" y2=\"4\"></line>\n");
      out.write("                        <line x1=\"6\" y1=\"20\" x2=\"6\" y2=\"14\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    Top 5 Hardware Más Vendido (Unidades Reales)\n");
      out.write("                </div>\n");
      out.write("                <div style=\"position: relative; height: 250px; width: 100%;\">\n");
      out.write("                    <canvas id=\"barChart\"></canvas>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"chart-box\" style=\"flex: 1;\">\n");
      out.write("                <div class=\"chart-title\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"18\" height=\"18\">\n");
      out.write("                        <path d=\"M21.21 15.89A10 10 0 1 1 8 2.83\"></path>\n");
      out.write("                        <path d=\"M22 12A10 10 0 0 0 12 2v10z\"></path>\n");
      out.write("                    </svg>\n");
      out.write("                    Distribución de Stock por Categoría\n");
      out.write("                </div>\n");
      out.write("                <div style=\"position: relative; height: 250px; width: 100%; display: flex; justify-content: center;\">\n");
      out.write("                    <canvas id=\"doughnutChart\"></canvas>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <h3 class=\"subtitle-blue mt-20 mb-15 d-flex align-center gap-10\">\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"18\" height=\"18\">\n");
      out.write("                <path d=\"M22 12h-4l-3 9L9 3l-3 9H2\"></path>\n");
      out.write("            </svg>\n");
      out.write("            Auditoría de Ventas en Vivo (Últimas 5 transacciones)\n");
      out.write("        </h3>\n");
      out.write("        \n");
      out.write("        <div class=\"table-panel mb-25\">\n");
      out.write("            <table class=\"tech-table\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>FECHA / HORA</th>\n");
      out.write("                        <th>COMPROBANTE</th>\n");
      out.write("                        <th>CLIENTE</th>\n");
      out.write("                        <th>PRODUCTO</th>\n");
      out.write("                        <th>TOTAL</th>\n");
      out.write("                        <th class=\"text-center\">ESTADO</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");

                        if(ultimasVentas != null && !ultimasVentas.isEmpty()) {
                            int count = 0;
                            for(Venta v : ultimasVentas) {
                                if(count >= 5) break;
                                boolean anulada = "ANULADA".equals(v.getEstado());
                    
      out.write("\n");
      out.write("                    <tr class=\"");
      out.print( anulada ? "row-disabled" : "" );
      out.write("\">\n");
      out.write("                        <td class=\"text-muted text-xs\">");
      out.print( sdf.format(v.getFecha()) );
      out.write("</td>\n");
      out.write("                        <td class=\"font-mono text-sm\">");
      out.print( v.getNroComprobante() );
      out.write("</td>\n");
      out.write("                        <td class=\"td-nombre\">");
      out.print( v.getNombreCliente() );
      out.write("</td>\n");
      out.write("                        <td class=\"text-sm\">");
      out.print( v.getNombreProducto() );
      out.write("</td>\n");
      out.write("                        <td class=\"font-mono text-success font-bold\">S/ ");
      out.print( String.format("%,.2f", v.getTotal()) );
      out.write("</td>\n");
      out.write("                        <td class=\"text-center\">\n");
      out.write("                            ");
 if(!anulada) { 
      out.write("\n");
      out.write("                                <span class=\"badge badge-optimal\">COMPLETADA</span>\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("                                <span class=\"badge badge-alert\">ANULADA</span>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");
      count++;
                            }
                        } else { 
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td colspan=\"6\" class=\"text-center p-30 text-muted\">\n");
      out.write("                            No hay transacciones recientes para mostrar en la auditoría.\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/reportes.js\"></script>\n");
      out.write("    <script>\n");
      out.write("        inicializarDashboard(\n");
      out.write("            [");
      out.print( request.getAttribute("topLabels") );
      out.write("], \n");
      out.write("            [");
      out.print( request.getAttribute("topData") );
      out.write("], \n");
      out.write("            [");
      out.print( request.getAttribute("catLabels") );
      out.write("], \n");
      out.write("            [");
      out.print( request.getAttribute("catData") );
      out.write("]\n");
      out.write("        );\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
