/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-27 18:59:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ferreteriacruz.modelo.Usuario;

public final class Usuarios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Usuario");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Usuario usuarioActivo = (Usuario) session.getAttribute("usuarioActivo");
    if (usuarioActivo == null) {
        response.sendRedirect("Login.jsp");
        return;
    }

    boolean esAdmin = "JEFE_ALMACEN".equals(usuarioActivo.getRol());

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>FerreteriaCruz | Gestión de Usuarios</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=JetBrains+Mono&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/estilos.css\">\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        \n");
      out.write("        <div class=\"header-tech\">\n");
      out.write("            <div class=\"header-title\">\n");
      out.write("                <h2>\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--brand-blue)\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" style=\"width: 24px; height: 24px;\">\n");
      out.write("                        <path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"></path>\n");
      out.write("                        <circle cx=\"9\" cy=\"7\" r=\"4\"></circle>\n");
      out.write("                        <path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"></path>\n");
      out.write("                        <path d=\"M16 3.13a4 4 0 0 1 0 7.75\"></path>\n");
      out.write("                    </svg>\n");
      out.write("                    Gestión de Personal (Módulo de Seguridad)\n");
      out.write("                </h2>\n");
      out.write("            </div>\n");
      out.write("            <a href=\"ProductoServlet?accion=listar\" class=\"btn-tech\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                    <line x1=\"19\" y1=\"12\" x2=\"5\" y2=\"12\"></line>\n");
      out.write("                    <polyline points=\"12 19 5 12 12 5\"></polyline>\n");
      out.write("                </svg>\n");
      out.write("                Volver al Inventario\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
 if(request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("            <div class=\"alert-error mb-15\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\"></line><line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\"></line></svg>\n");
      out.write("                <span>");
      out.print( request.getAttribute("error") );
      out.write("</span>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"grid-container\">\n");
      out.write("            \n");
      out.write("            <div class=\"form-side\">\n");
      out.write("                <h3 class=\"subtitle-blue\">Registrar Nuevo Operario</h3>\n");
      out.write("                \n");
      out.write("                ");
 if(esAdmin) { 
      out.write("\n");
      out.write("                    <form action=\"UsuarioServlet?accion=registrar\" method=\"POST\">\n");
      out.write("                        <label for=\"txtUsername\" class=\"form-label\">Nombre de Usuario (Login):</label>\n");
      out.write("                        <input type=\"text\" id=\"txtUsername\" name=\"txtUsername\" class=\"input-tech\" required autocomplete=\"off\" placeholder=\"Ej. jperez\">\n");
      out.write("\n");
      out.write("                        <label for=\"txtPassword\" class=\"form-label\">Contraseña de acceso:</label>\n");
      out.write("                        <input type=\"password\" id=\"txtPassword\" name=\"txtPassword\" class=\"input-tech\" required placeholder=\"••••••••\">\n");
      out.write("\n");
      out.write("                        <label for=\"cboRol\" class=\"form-label\">Rol en el Sistema:</label>\n");
      out.write("                        <select id=\"cboRol\" name=\"cboRol\" class=\"input-tech\" required>\n");
      out.write("                            <option value=\"ALMACEN\">Operario de Almacén</option>\n");
      out.write("                            <option value=\"JEFE_ALMACEN\">Jefe de Almacén (Admin)</option>\n");
      out.write("                        </select>\n");
      out.write("\n");
      out.write("                        <button type=\"submit\" class=\"btn-submit-tech mt-15\">\n");
      out.write("                            Guardar Credenciales\n");
      out.write("                        </button>\n");
      out.write("                    </form>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <div class=\"note-box mt-20\">\n");
      out.write("                        <h4 class=\"text-warning d-flex align-center gap-10 mb-15 mt-0 text-sm\">\n");
      out.write("                            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" width=\"16\" height=\"16\">\n");
      out.write("                                <path d=\"M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z\"></path>\n");
      out.write("                                <line x1=\"12\" y1=\"9\" x2=\"12\" y2=\"13\"></line>\n");
      out.write("                                <line x1=\"12\" y1=\"17\" x2=\"12.01\" y2=\"17\"></line>\n");
      out.write("                            </svg>\n");
      out.write("                            Acceso Denegado\n");
      out.write("                        </h4>\n");
      out.write("                        <p class=\"text-muted text-xs\">Solo el perfil <strong>'JEFE_ALMACEN'</strong> puede registrar nuevos usuarios en el sistema.</p>\n");
      out.write("                    </div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"table-side\">\n");
      out.write("                <div class=\"d-flex justify-between align-center mb-15\">\n");
      out.write("                    <h3 class=\"text-white font-bold m-0\">Personal Autorizado</h3>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"search-box-container mb-15\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#6b7280\" stroke-width=\"2\" width=\"16\" height=\"16\">\n");
      out.write("                        <circle cx=\"11\" cy=\"11\" r=\"8\"></circle>\n");
      out.write("                        <line x1=\"21\" y1=\"21\" x2=\"16.65\" y2=\"16.65\"></line>\n");
      out.write("                    </svg>\n");
      out.write("                    <input type=\"text\" id=\"buscadorUsuarios\" placeholder=\"Buscar usuario o rol...\" class=\"input-tech m-0\" style=\"max-width: none;\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"table-panel\">\n");
      out.write("                    <table class=\"tech-table\" id=\"tablaUsuarios\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>ID SYS</th>\n");
      out.write("                                <th>Nombre de Usuario</th>\n");
      out.write("                                <th class=\"text-center\">Rol de Seguridad</th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            ");

                                List<Usuario> lista = (List<Usuario>) request.getAttribute("listaUsuarios");
                                if (lista != null && !lista.isEmpty()) {
                                    for (Usuario u : lista) {
                                        String badgeClase = u.getRol().equals("JEFE_ALMACEN") ? "badge-role-admin" : "badge-role-user";
                            
      out.write("\n");
      out.write("                                <tr>\n");
      out.write("                                    <td class=\"td-id\">USR-");
      out.print( String.format("%03d", u.getIdUsuario()) );
      out.write("</td>\n");
      out.write("                                    <td class=\"font-bold text-white\">");
      out.print( u.getUsername() );
      out.write("</td>\n");
      out.write("                                    <td class=\"text-center\">\n");
      out.write("                                        <span class=\"badge ");
      out.print( badgeClase );
      out.write("\">\n");
      out.write("                                            ");
      out.print( u.getRol() );
      out.write("\n");
      out.write("                                        </span>\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            ");

                                    }
                                } else {
                            
      out.write("\n");
      out.write("                                <tr><td colspan=\"3\" class=\"text-center p-30 text-muted\">No hay registros disponibles.</td></tr>\n");
      out.write("                            ");
  } 
      out.write("\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("                        \n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/assets/js/utils.js\"></script>\n");
      out.write("    <script>inicializarBuscador('buscadorUsuarios', 'tablaUsuarios');</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
