/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.52
 * Generated at: 2026-02-27 18:59:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ferreteriacruz.modelo.Producto;
import ferreteriacruz.servicio.ServicioProducto;
import ferreteriacruz.modelo.Usuario;

public final class Venta_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("ferreteriacruz.modelo.Producto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ferreteriacruz.modelo.Usuario");
    _jspx_imports_classes.add("ferreteriacruz.servicio.ServicioProducto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    Usuario usuarioActivo = (Usuario) session.getAttribute("usuarioActivo");
    if (usuarioActivo == null) {
        response.sendRedirect("Login.jsp");
        return;
    }
    ServicioProducto sProducto = new ServicioProducto();
    List<Producto> listaProductos = sProducto.obtenerInventarioActivo();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>ferreteriaCruz | Registro de Salidas</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@500;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/css/estilos.css\">\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    \n");
      out.write("    <div class=\"dashboard-container-narrow\">\n");
      out.write("        \n");
      out.write("        <div class=\"header-tech\">\n");
      out.write("            <div class=\"header-title\">\n");
      out.write("                <img src=\"");
      out.print(request.getContextPath());
      out.write("/assets/img/logo_ferreteriacruz.png\" alt=\"FerreteriaCruz\" class=\"logo-img\" onerror=\"this.src='https://via.placeholder.com/150x45/111827/E63946?text=FERRETERIACRUZ'\">\n");
      out.write("                <h2>\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"24\" height=\"24\" class=\"text-blue\">\n");
      out.write("                        <circle cx=\"9\" cy=\"21\" r=\"1\"></circle><circle cx=\"20\" cy=\"21\" r=\"1\"></circle>\n");
      out.write("                        <path d=\"M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6\"></path>\n");
      out.write("                    </svg>\n");
      out.write("                    Terminal de Salida / Venta\n");
      out.write("                </h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"nav-links\">\n");
      out.write("                <a href=\"VentaServlet?accion=historial\" class=\"btn-tech btn-primary-tech\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"16\" height=\"16\">\n");
      out.write("                        <circle cx=\"12\" cy=\"12\" r=\"10\"></circle><polyline points=\"12 6 12 12 16 14\"></polyline>\n");
      out.write("                    </svg>\n");
      out.write("                    Historial y Anulaciones\n");
      out.write("                </a>\n");
      out.write("                <a href=\"ProductoServlet?accion=listar\" class=\"btn-tech\">\n");
      out.write("                    Volver al Inventario\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"info-box mb-25\">\n");
      out.write("            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--brand-blue)\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"20\" height=\"20\">\n");
      out.write("                <circle cx=\"12\" cy=\"12\" r=\"10\"></circle><line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"12\"></line><line x1=\"12\" y1=\"8\" x2=\"12.01\" y2=\"8\"></line>\n");
      out.write("            </svg>\n");
      out.write("            <p class=\"text-muted text-sm m-0\">Proceso Transaccional: El stock será descontado inmediatamente en MySQL y reportado al Kardex. Cantidad bloqueada a 1 para garantizar la Trazabilidad del Número de Serie.</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"form-panel\">\n");
      out.write("            <h3 class=\"mb-25\">\n");
      out.write("                <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"var(--brand-blue)\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"18\" height=\"18\">\n");
      out.write("                    <rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\" ry=\"2\"></rect><line x1=\"8\" y1=\"21\" x2=\"16\" y2=\"21\"></line><line x1=\"12\" y1=\"17\" x2=\"12\" y2=\"21\"></line>\n");
      out.write("                </svg>\n");
      out.write("                Asignación de Activo (Hardware)\n");
      out.write("            </h3>\n");
      out.write("            \n");
      out.write("            <form action=\"VentaServlet\" method=\"POST\">\n");
      out.write("                \n");
      out.write("                <label for=\"cboProducto\" class=\"form-label\">Componente a despachar (SKU):</label>\n");
      out.write("                <select id=\"cboProducto\" name=\"cboProducto\" class=\"input-tech\" required>\n");
      out.write("                    <option value=\"\" disabled selected>-- Inicialice escaneo o seleccione de la lista --</option>\n");
      out.write("                    ");

                        ferreteriacruz.dao.SeriesDAO serieDao = new ferreteriacruz.dao.SeriesDAO();
                        if (listaProductos != null) {
                            for (Producto p : listaProductos) {
                                if (p.getStockActual() > 0) {
                                    java.util.List<ferreteriacruz.modelo.Series> seriesDisp = serieDao.listarSeriesDisponibles(p.getIdProducto());
                                    StringBuilder sbSeries = new StringBuilder();
                                    for(ferreteriacruz.modelo.Series s : seriesDisp) {
                                        sbSeries.append(s.getNumeroSerie()).append(",");
                                    }
                                    String strSeries = sbSeries.toString();
                                    if(strSeries.length() > 0) strSeries = strSeries.substring(0, strSeries.length() - 1);
                    
      out.write("\n");
      out.write("                                    <option value=\"");
      out.print( p.getIdProducto() );
      out.write("\" data-series=\"");
      out.print( strSeries );
      out.write("\">\n");
      out.write("                                        [");
      out.print( p.getCodigoSKU() );
      out.write("] - ");
      out.print( p.getNombre() );
      out.write(" (Stock disp: ");
      out.print( p.getStockActual() );
      out.write(")\n");
      out.write("                                    </option>\n");
      out.write("                    ");

                                }
                            }
                        }
                    
      out.write("\n");
      out.write("                </select>\n");
      out.write("\n");
      out.write("                <label for=\"txtNroSerie\" class=\"form-label\">Número de Serie (S/N):</label>\n");
      out.write("                <select id=\"txtNroSerie\" name=\"txtNroSerie\" class=\"input-tech input-mono\" required>\n");
      out.write("                    <option value=\"\" disabled selected>-- Primero seleccione un componente --</option>\n");
      out.write("                </select>\n");
      out.write("\n");
      out.write("                <div class=\"d-flex gap-15 mb-25\" style=\"flex-wrap: wrap;\">\n");
      out.write("                    \n");
      out.write("                    <div class=\"flex-col-0-8\">\n");
      out.write("                        <label for=\"txtCantidad\" class=\"form-label\">Cant.</label>\n");
      out.write("                        <input type=\"number\" id=\"txtCantidad\" name=\"txtCantidad\" class=\"input-tech input-readonly input-mono m-0\" value=\"1\" min=\"1\" required readonly>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"flex-col-1-5\">\n");
      out.write("                        <label for=\"cboTipoComprobante\" class=\"form-label\">Tipo de Doc:</label>\n");
      out.write("                        <select id=\"cboTipoComprobante\" name=\"cboTipoComprobante\" class=\"input-tech m-0\" required>\n");
      out.write("                            <option value=\"BOLETA\">Boleta</option>\n");
      out.write("                            <option value=\"FACTURA\">Factura</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"flex-col-1-5\">\n");
      out.write("                        <label for=\"txtComprobante\" class=\"form-label\">Nro. de Ticket:</label>\n");
      out.write("                        <input type=\"text\" id=\"txtComprobante\" name=\"txtComprobante\" class=\"input-tech input-mono m-0\" required placeholder=\"Ej. TCK-00452\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"flex-col-1-5\">\n");
      out.write("                        <label for=\"cboMetodoPago\" class=\"form-label\">Método de Pago:</label>\n");
      out.write("                        <div class=\"payment-selector-container\">\n");
      out.write("                            <label class=\"payment-option\">\n");
      out.write("                                <input type=\"radio\" name=\"cboMetodoPago\" value=\"EFECTIVO\" checked>\n");
      out.write("                                <div class=\"payment-content\">\n");
      out.write("                                    <img src=\"assets/img/icono-efectivo.png\" alt=\"Efectivo\">\n");
      out.write("                                    <span>Efectivo</span>\n");
      out.write("                                </div>\n");
      out.write("                            </label>\n");
      out.write("\n");
      out.write("                            <label class=\"payment-option\">\n");
      out.write("                                <input type=\"radio\" name=\"cboMetodoPago\" value=\"TARJETA\">\n");
      out.write("                                <div class=\"payment-content\">\n");
      out.write("                                    <img src=\"assets/img/icono-tarjeta.png\" alt=\"Tarjeta\">\n");
      out.write("                                    <span>Tarjeta</span>\n");
      out.write("                                </div>\n");
      out.write("                            </label>\n");
      out.write("\n");
      out.write("                            <label class=\"payment-option\">\n");
      out.write("                                <input type=\"radio\" name=\"cboMetodoPago\" value=\"TRANSFERENCIA\">\n");
      out.write("                                <div class=\"payment-content\">\n");
      out.write("                                    <img src=\"assets/img/icono-transfer.png\" alt=\"Transferencia\">\n");
      out.write("                                    <span>Transfer.</span>\n");
      out.write("                                </div>\n");
      out.write("                            </label>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"info-box mt-20 p-20\" style=\"display: block; border-left-color: var(--brand-blue);\">\n");
      out.write("                    <h4 class=\"text-blue text-sm mb-15 mt-0 font-bold\">Datos del Cliente (Facturación)</h4>\n");
      out.write("                    \n");
      out.write("                    <div class=\"d-flex gap-15\" style=\"flex-wrap: wrap;\">\n");
      out.write("                        <div class=\"flex-col\">\n");
      out.write("                            <label class=\"form-label\">DNI / RUC:</label>\n");
      out.write("                            <input type=\"text\" name=\"txtDocCliente\" class=\"input-tech input-mono m-0\" required placeholder=\"Ej. 70123456\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"flex-col-1-5\">\n");
      out.write("                            <label class=\"form-label\">Nombre o Razón Social:</label>\n");
      out.write("                            <input type=\"text\" name=\"txtNombreCliente\" class=\"input-tech m-0\" required placeholder=\"Ej. Juan Pérez\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"flex-col-1-5\">\n");
      out.write("                            <label class=\"form-label\">Correo Electrónico:</label>\n");
      out.write("                            <input type=\"email\" name=\"txtCorreoCliente\" class=\"input-tech m-0\" placeholder=\"correo@empresa.com\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn-submit-tech mt-20\">\n");
      out.write("                    <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" width=\"20\" height=\"20\">\n");
      out.write("                        <line x1=\"5\" y1=\"12\" x2=\"19\" y2=\"12\"></line><polyline points=\"12 5 19 12 12 19\"></polyline>\n");
      out.write("                    </svg>\n");
      out.write("                    Confirmar Salida de Inventario\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script src=\"assets/js/venta.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
