# ===============================
# CONFIGURACIÓN DE BD (PRODUCCIÓN)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# PUERTO DEL SERVIDOR
# ===============================
server.port=${PORT:8080}